# Generated by Django 3.0.3 on 2020-07-30 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0006_auto_20200730_2005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-pub_date']},
        ),
    ]
